### ISSUE TITLE
Cannot sign up - username is already in use

### ISSUE THREAD

**Issue by k3nda** [bytemedrive/android#148]
Try to sign up for example with username `WhyICantSignIn` and error shows up.

**Comment by Blizard** [comment]
`
Signup failed for username: kjffgjh
                                                                                                    java.security.NoSuchAlgorithmException: The BC provider no longer provides an implementation for Cipher.AES/GCM/NoPadding.  Please see https://android-developers.googleblog.com/2018/03/cryptography-changes-in-android-p.html for more details.
                                                                                                    	at sun.security.jca.Providers.checkBouncyCastleDeprecation(Providers.java:563)
                                                                                                    	at sun.security.jca.Providers.checkBouncyCastleDeprecation(Providers.java:346)
                                                                                                    	at javax.crypto.Cipher.createCipher(Cipher.java:722)
                                                                                                    	at javax.crypto.Cipher.getInstance(Cipher.java:717)
                                                                                                    	at javax.crypto.Cipher.getInstance(Cipher.java:674)
                                                                                                    	at com.bytemedrive.privacy.AesService.encryptWithKey(AesService.kt:45)
                                                                                                    	at com.bytemedrive.privacy.AesService.encryptWithPassword(AesService.kt:39)
                                                                                                    	at com.bytemedrive.signup.SignUpViewModel$signUp$1.invokeSuspend(SignUpViewModel.kt:51)
                                                                                                    	at com.bytemedrive.signup.SignUpViewModel$signUp$1.invoke(Unknown Source:8)
                                                                                                    	at com.bytemedrive.signup.SignUpViewModel$signUp$1.invoke(Unknown Source:2)
                                                                                                    	at com.bytemedrive.signup.SignUpViewModel$effect$1.invokeSuspend(SignUpViewModel.kt:80)
                                                                                                    	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
`

MIUI version: MIUI Global 12.0.5 Stable
Android version 10 QKQ1.190825.002

**Comment by Blizard** [comment]
https://android-developers.googleblog.com/2018/03/cryptography-changes-in-android-p.html
