### ISSUE TITLE
mac check in GCM failed

### ISSUE THREAD

**Issue by tonda100** [bytemedrive/android#154]
```
2023-12-10 00:45:07.847 17852-17875 com.bytemedrive         com.bytemedrive                      I  NativeAlloc concurrent copying GC freed 156794(8259KB) AllocSpace objects, 236(9580KB) LOS objects, 75% free, 20MB/80MB, paused 165us,102us total 109.068ms
2023-12-10 00:45:08.088 17852-17946 com.byteme...nailCreate com.bytemedrive                      I  Uploading thumbnail with resolution P360 for file id=8ca4945d-911d-4912-97f0-2b05693070fe.
2023-12-10 00:45:08.172 17852-17946 com.byteme...tPublisher com.bytemedrive                      I  Publishing event FILE_THUMBNAIL_UPLOADED with id: 8e155d70-6a87-4d92-9c8f-3f997d3a2a1e
2023-12-10 00:45:08.188 17852-17946 io.ktor.cl...HttpClient com.bytemedrive                      I  Sending request POST https://api.bytemedrive.com/customers/fea7718fd3f6caba836bca62326b35a92829194885bb86eeb6fab2638aaaa6c0/events
2023-12-10 00:45:08.437 17852-17852 Choreographer           com.bytemedrive                      I  Skipped 210 frames!  The application may be doing too much work on its main thread.
2023-12-10 00:45:08.441 17852-17852 Main Screen             com.bytemedrive                      E  mac check in GCM failed
                                                                                                    javax.crypto.AEADBadTagException: mac check in GCM failed
                                                                                                    	at java.lang.reflect.Constructor.newInstance0(Native Method)
                                                                                                    	at java.lang.reflect.Constructor.newInstance(Constructor.java:343)
                                                                                                    	at com.android.org.bouncycastle.jcajce.provider.symmetric.util.BaseBlockCipher$AEADGenericBlockCipher.doFinal(BaseBlockCipher.java:1534)
                                                                                                    	at com.android.org.bouncycastle.jcajce.provider.symmetric.util.BaseBlockCipher.engineDoFinal(BaseBlockCipher.java:1244)
                                                                                                    	at javax.crypto.Cipher.doFinal(Cipher.java:2056)
                                                                                                    	at com.bytemedrive.privacy.AesService.decryptWithKey(AesService.kt:87)
                                                                                                    	at com.bytemedrive.service.ServiceThumbnailDownload$onStartCommand$1$1.invokeSuspend(ServiceThumbnailDownload.kt:57)
                                                                                                    	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
                                                                                                    	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:104)
                                                                                                    	at kotlinx.coroutines.internal.LimitedDispatcher.run(LimitedDispatcher.kt:42)
                                                                                                    	at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:95)
                                                                                                    	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:570)
                                                                                                    	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
                                                                                                    	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:677)
                                                                                                    	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:664)
                                                                                                    	Suppressed: kotlinx.coroutines.DiagnosticCoroutineContextException: [StandaloneCoroutine{Cancelled}@47c00bb, Dispatchers.Default]
2023-12-10 00:45:08.453 17852-17852 WindowOnBackDispatcher  com.bytemedrive                      W  OnBackInvokedCallback is not enabled for the application.
                                                                                                    Set 'android:enableOnBackInvokedCallback="true"' in the application manifest.
2023-12-10 00:45:08.454 17852-17920 Parcel                  com.bytemedrive                      W  Expecting binder but got null!
2023-12-10 00:45:08.483 17852-17907 OpenGLRenderer          com.bytemedrive                      E  Unable to match the desired swap behavior.
2023-12-10 00:45:08.495 17852-17852 Compatibil...geReporter com.bytemedrive                      D  Compat change id reported: 78294732; UID 10227; state: ENABLED
2023-12-10 00:45:08.497 17852-17882 OpenGLRenderer          com.bytemedrive                      I  Davey! duration=3561ms; Flags=1, FrameTimelineVsyncId=14177452, IntendedVsync=92942029566244, Vsync=92945538820594, InputEventId=0, HandleInputStart=92945539979838, AnimationStart=92945539981296, PerformTraversalsStart=92945567560310, DrawStart=92945587355937, FrameDeadline=92942050066244, FrameInterval=92945539749005, FrameStartTime=16710735, SyncQueued=92945588260572, SyncStart=92945588336718, IssueDrawCommandsStart=92945588384270, SwapBuffers=92945589999010, FrameCompleted=92945590922760, DequeueBufferDuration=12239, QueueBufferDuration=257552, GpuCompleted=92945590922760, SwapBuffersCompleted=92945590517395, DisplayPresentTime=0, CommandSubmissionCompleted=92945589999010, 
2023-12-10 00:45:08.497 17852-17882 OpenGLRenderer          com.bytemedrive                      I  Davey! duration=3548ms; Flags=0, FrameTimelineVsyncId=14177452, IntendedVsync=92942029566244, Vsync=92945538820594, InputEventId=0, HandleInputStart=92945539979838, AnimationStart=92945539981296, PerformTraversalsStart=92945567560310, DrawStart=92945567595570, FrameDeadline=92944089176310, FrameInterval=92945539749005, FrameStartTime=16710735, SyncQueued=92945573797394, SyncStart=92945573847237, IssueDrawCommandsStart=92945573945519, SwapBuffers=92945575496248, FrameCompleted=92945577883227, DequeueBufferDuration=24479, QueueBufferDuration=253698, GpuCompleted=92945577883227, SwapBuffersCompleted=92945576087446, DisplayPresentTime=0, CommandSubmissionCompleted=92945575496248, 
2023-12-10 00:45:08.533 17852-17915 io.ktor.cl...HttpClient com.bytemedrive                      I  Response[204] in 345ms for request POST https://api.bytemedrive.com/customers/fea7718fd3f6caba836bca62326b35a92829194885bb86eeb6fab2638aaaa6c0/events
2023-12-10 00:45:08.533 17852-17915 com.byteme...yptedPrefs com.bytemedrive                      I  EncryptedPrefs storing 1 events
2023-12-10 00:45:08.683 17852-17915 io.ktor.cl...HttpClient com.bytemedrive                      I  Sending request GET https://api.bytemedrive.com/wallets/24465b45-c8f7-48ec-b769-f9b34bbb6bf1
2023-12-10 00:45:08.830 17852-17945 io.ktor.cl...HttpClient com.bytemedrive                      I  Response[200] in 147ms for request GET https://api.bytemedrive.com/wallets/24465b45-c8f7-48ec-b769-f9b34bbb6bf1
2023-12-10 00:45:08.833 17852-17949 com.byteme...yncService com.bytemedrive                      I  Customer refreshed.
2023-12-10 00:45:08.833 17852-17949 com.byteme...Repository com.bytemedrive                      I  Uploading chunk view id=57367a57-fde0-4b33-975e-d7d85d123eed num=0
2023-12-10 00:45:08.839 17852-17949 io.ktor.cl...HttpClient com.bytemedrive                      I  Sending request POST https://api.bytemedrive.com/wallets/24465b45-c8f7-48ec-b769-f9b34bbb6bf1/files
2023-12-10 00:45:09.068 17852-17875 com.bytemedrive         com.bytemedrive                      I  NativeAlloc concurrent copying GC freed 412893(14MB) AllocSpace objects, 197(35MB) LOS objects, 75% free, 17MB/69MB, paused 172us,39us total 116.458ms
2023-12-10 00:45:09.877 17852-17949 io.ktor.cl...HttpClient com.bytemedrive                      I  Response[204] in 1038ms for request POST https://api.bytemedrive.com/wallets/24465b45-c8f7-48ec-b769-f9b34bbb6bf1/files
2023-12-10 00:45:09.878 17852-17918 com.byteme...Repository com.bytemedrive                      I  Chunk view id=57367a57-fde0-4b33-975e-d7d85d123eed was uploaded
2023-12-10 00:45:09.878 17852-17918 com.byteme...Repository com.bytemedrive                      I  Uploading chunk view id=cdee8297-e986-44ed-a90e-aede44227a4f num=1
2023-12-10 00:45:09.879 17852-17918 io.ktor.cl...HttpClient com.bytemedrive                      I  Sending request POST https://api.bytemedrive.com/wallets/24465b45-c8f7-48ec-b769-f9b34bbb6bf1/files
2023-12-10 00:45:10.512 17852-17969 ProfileInstaller        com.bytemedrive                      D  Installing profile for com.bytemedrive
2023-12-10 00:45:10.608 17852-17918 io.ktor.cl...HttpClient com.bytemedrive                      I  Response[204] in 728ms for request POST https://api.bytemedrive.com/wallets/24465b45-c8f7-48ec-b769-f9b34bbb6bf1/files
2023-12-10 00:45:10.609 17852-17918 com.byteme...Repository com.bytemedrive                      I  Chunk view id=cdee8297-e986-44ed-a90e-aede44227a4f was uploaded
2023-12-10 00:45:10.610 17852-17918 com.byteme...nailCreate com.bytemedrive                      I  Missing thumbnail with resolution P1280 for file chunk view ids=[aa37f3b4-20c3-4850-9e69-a9529877e851, 897e970e-ecd6-459a-aa5c-1119653eeb31].
2023-12-10 00:45:10.618 17852-17918 io.ktor.cl...HttpClient com.bytemedrive                      I  Sending request GET https://api.bytemedrive.com/files/aa37f3b4-20c3-4850-9e69-a9529877e851
2023-12-10 00:45:10.907 17852-17899 io.ktor.cl...HttpClient com.bytemedrive                      I  Response[200] in 289ms for request GET https://api.bytemedrive.com/files/aa37f3b4-20c3-4850-9e69-a9529877e851
```

**Comment by tonda100** [comment]
The issue is that there is thumbnail-uploded event without available data on a server. We need to make sure file was uploaded by emitting event before upload and also after upload.
We also need to make sure there is correct numbet of thumbnails for a source file.
