### ISSUE TITLE
Buffer underflow exception when uploading big file

### ISSUE THREAD

**Issue by Blizard** [bytemedrive/android#94]
```
2023-10-16 06:23:51.423 13807-13807 Main Screen             com.bytemedrive                      E  null
                                                                                                    java.nio.BufferUnderflowException
                                                                                                    	at java.nio.HeapByteBuffer.get(HeapByteBuffer.java:123)
                                                                                                    	at java.nio.ByteBuffer.get(ByteBuffer.java:557)
                                                                                                    	at com.bytemedrive.privacy.AesService.decryptWithKey(AesService.kt:82)
                                                                                                    	at com.bytemedrive.file.root.FileViewModel.findThumbnailForDataFileLink(FileViewModel.kt:269)
                                                                                                    	at com.bytemedrive.file.root.FileViewModel.access$findThumbnailForDataFileLink(FileViewModel.kt:32)
                                                                                                    	at com.bytemedrive.file.root.FileViewModel$findThumbnailForDataFileLink$1.invokeSuspend(Unknown Source:15)
                                                                                                    	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
                                                                                                    	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:104)
                                                                                                    	at kotlinx.coroutines.EventLoop.processUnconfinedEvent(EventLoop.common.kt:69)
                                                                                                    	at kotlinx.coroutines.internal.DispatchedContinuation.resumeWith(DispatchedContinuation.kt:355)
                                                                                                    	at io.ktor.util.pipeline.SuspendFunctionGun.resumeRootWith(SuspendFunctionGun.kt:135)
                                                                                                    	at io.ktor.util.pipeline.SuspendFunctionGun.loop(SuspendFunctionGun.kt:109)
                                                                                                    	at io.ktor.util.pipeline.SuspendFunctionGun.access$loop(SuspendFunctionGun.kt:11)
                                                                                                    	at io.ktor.util.pipeline.SuspendFunctionGun$continuation$1.resumeWith(SuspendFunctionGun.kt:59)
                                                                                                    	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:46)
                                                                                                    	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
                                                                                                    	at android.os.Handler.handleCallback(Handler.java:938)
                                                                                                    	at android.os.Handler.dispatchMessage(Handler.java:99)
                                                                                                    	at android.os.Looper.loopOnce(Looper.java:201)
                                                                                                    	at android.os.Looper.loop(Looper.java:288)
                                                                                                    	at android.app.ActivityThread.main(ActivityThread.java:7839)
                                                                                                    	at java.lang.reflect.Method.invoke(Native Method)
                                                                                                    	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
                                                                                                    	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1003)
                                                                                                    	Suppressed: kotlinx.coroutines.DiagnosticCoroutineContextException: [StandaloneCoroutine{Cancelled}@d0e5eff, Dispatchers.Main.immediate]
```

**Comment by k3nda** [comment]
Raised when BE has missing chunk. Should be fixed already on BE
